version: 2
updates:
    - package-ecosystem: cargo
      directory: '/'
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
      groups:
          dioxus:
              patterns: ['dioxus*']
          smooai:
              patterns: ['smooai-*']

    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: monthly
